#!/bin/bash

# sysinfo_page - Un script que produce un archivo HTML
##### Constantes
TITLE="Información del sistema para $HOSTNAME"
RIGHT_NOW=$(date +"%x %r")
TIME_STAMP="Actualizada el $RIGHT_NOW por $USER"
##### Funciones
system_info()
{

  echo "<h2>Información de versión del sistema</h2>"
  echo "<pre>"
  lsb_release -a 
  echo "</pre>"

}


show_uptime()
{

   echo "<h2>Tiempo de encendido del sistema</h2>"
   echo "<pre>"
   uptime
   echo "</pre>"

}


drive_space()
{
   echo "<h2>Información del Disco Duro y sus particiones</h2>"
   echo "<pre>"
   df
   echo "</pre>"
}


home_space()
{
 echo "<p>Información del espacio ocupado</p>"
 echo "<pre>"
 if [ "$USER" = "root" ];
 then du -s /home/* | sort -nr
 else
 du -s /home/$USER | sort -nr
 fi
 echo  "</pre>"

}


pro() #Función que muestra todos los procesos de todas las terminales en orden inverso (Modificación)
{

echo "<p>Información de los procesos de todas las terminales</p>"
echo "<pre>"
  ps -x | sort -nr 
echo  "</pre>"


}
##### Programa principal

cat << _EOF_
<html>
<head> <meta http-equiv="Content-Type" content="text/html; charset=utf-8">
  
  <title>$TITLE</title>
  
</head>

<body>
  <h1>$TITLE</h1>
   <p>$TIME_STAMP</p>
   $(system_info)
   $(show_uptime)
   $(drive_space)
   $(home_space)
   $(pro)
</body>
</html>
_EOF_
